### ISSUE TITLE
File wont parse?

### ISSUE THREAD

**Issue by willybeans** [jscomplete/learn-fullstack-javascript#1]
When i try to "npm run dev" in console im getting this error: 

ERROR in ./src/testData.json
Module build failed: SyntaxError: Unexpected token 
 in JSON at position 262
    at Object.parse (native)
    at Object.module.exports (/Users/williamwedmedyk/jsPrac/jscomplete/node_modules/json-loader/index.js:11:48)
 @ ./src/index.js 11:16-37

here is my index.js file: 
  5 module.exports = function(source) {
  6 
  7         if (typeof source === "string" && source.indexOf("module.exports = ")     === 0) {
  8         return source;
  9     }
 10         this.cacheable && this.cacheable();
 11         var value = typeof source === "string" ? JSON.parse(source) : source;
 12         this.value = [value]; 13         return "module.exports = " + JSON.stringify(value, undefined, "\t") +     ";";
 14 }

**Comment by samerbuna** [comment]
@willybeans did you figure this out?
