### ISSUE TITLE
'webpack' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rakeshrudrapaul** [jscomplete/learn-fullstack-javascript#6]
Hi   $ npm run dev command give me error

> fresh@1.0.0 dev C:\xampp\htdocs\react
> webpack -wd

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fresherhub@1.0.0 dev: `webpack -wd`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fresherhub@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**package.json**

  "dependencies": {
    "body-parser": "^1.15.2",
    "bootstrap": "^3.3.7",
    "ejs": "^2.5.2",
    "express": "^4.14.0",
    "jquery": "^3.3.1",
    "json-loader": "^0.5.4",
    "mongodb": "^2.2.10",
    "node-sass-middleware": "^0.9.8",
    "react": "^15.3.2",
    "react-dom": "^15.3.2"
  },
  "devDependencies": {
    "babel-cli": "^6.16.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.17.0",
    "eslint": "^3.7.1",
    "eslint-plugin-react": "^6.4.0",
    "nodemon": "^1.11.0",
    "webpack": "^1.13.2"
  }

**Comment by MohamedMFouad** [comment]
i try cli webpack and the same

**Comment by badarshahzad** [comment]
I am also facing the same error!

**Comment by samerbuna** [comment]
Please add the webpack-cli package. The `webpack` command is now part of that package:

```
npm i webpack-cli
```

**Comment by badarshahzad** [comment]
@samerbuna 
check the below package.json file and the command results?
```
{
  "name": "learning-fullstack-javascript",
  "version": "1.0.0",
  "description": "Learning fullstack JavaScript Development: MongoDB, Node.js, React.js",
  "main": "index.js",
  "scripts": {
    "start": "nodemon --exec babel-node server.js --ignore public/",
    "dev": "webpack -wd"
  },
  "repository": {
    "type": "git",
    "url": "(https://github.com/badarshahzad/learning-fullstack-javascript.git)"
  },
  "keywords": [
    "React",
    "Javacript",
    "NodeJs",
    "MongoDB"
  ],
  "author": "@badarshahzad",
  "license": "GPL-3.0",
  "dependencies": {
    "ejs": "^2.6.1",
    "express": "^4.16.3",
    "mongodb": "^3.0.10",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "webpack": "^4.10.2",
    "webpack-cli": "^3.0.1"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.8.2",
    "nodemon": "^1.17.5"
  }
}

```
```
 badar:learning-fullstack-javascript$ npm run dev

> learning-fullstack-javascript@1.0.0 dev /home/badar/Desktop/learning-fullstack-javascript
> webpack -wd

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! learning-fullstack-javascript@1.0.0 dev: `webpack -wd`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the learning-fullstack-javascript@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by samerbuna** [comment]
@badarshahzad the Webpack configuration syntax has changed a bit on Webpack 4.

Probably the easiest solution for this course is to use Webpack 3.x instead

```
npm install webpack@3
```

**Comment by richhauck** [comment]
Webpack 4 changed its configuration structure (see [webpack configuration](https://webpack.js.org/configuration/) ). I found that if you install webpack and webpack-cli, then change your webpack.config.js to the following:

```
module.exports = {
    entry: './src/index.js',
    output: {
        path: __dirname + '/public',
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader'
            }
        ]
    }
}
```

It works.

**Comment by Shweta-Kalariya** [comment]
This doesn't work for me.

**Comment by samerbuna** [comment]
All the files and tags of this repo were updated for things to work with the latest changes in the tools.

**Comment by sreerajms4u** [comment]
There is a chance for wrong place compilation. If you are tried to run the command under src folder, then this error will show.

**Comment by Enache-Ionut** [comment]
I have the same issue. I'm using webpack@4.41.2

**Comment by maang-io** [comment]
I am surprised that this issue has still not been resolved or am I missing sth? I am still hitting the same issue, using webpack 5.65.0 and webpack-cli 4.9.1

**Comment by manmysgit** [comment]
same issue with below config    
"webpack-cli": "^5.0.0",
    "webpack-dev-server": "^4.15.1",
    "webpack": "^5.88.1"
