### ISSUE TITLE
Error: Can not find module "http"

### ISSUE THREAD

**Issue by divyanksharma** [jscomplete/learn-fullstack-javascript#8]
Hi, Your tutorial on Full stack is very helpful to learn JS. However, I am facing an issue while importing http module in server.js. It says can not find module "http". I am using a windows environment. Is there a work around to this situation. 
P.S. - Https gets imported successfully

**Comment by samerbuna** [comment]
It seems like your Node installation on Windows was done with certain options that configured it to skip the http module. I'd try to uninstall/reinstall Node.
